export const endpoints = {
  authRefreshToken: '/auth/token',
  authLogin: '/auth/login',
  authRegister: '/auth/register',
  authGetProfile: '/auth/profile',
  authUpdateProfile: '/auth/profile',
  authLogout: '/auth/logout',
  authForgotPassword: '/auth/forgot-password',
  authResetPassword: '/auth/reset-password',
  authUploadAvatar: '/auth/avatar/upload',
  authChangePassword: '/auth/change-password',
  userGetInfo: '/users',
  messagesGet: '/messages',
  conversationsUploadPhoto: '/conversations/change-photo',
  conversationsChangeRole: '/conversations/change-role',
};
